# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(default=True, max_length=100, null=True, verbose_name='Видео'),
        ),
    ]
