# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170530_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(default=True, max_length=100, verbose_name='Видео'),
        ),
    ]
