# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Вывести в блог'),
        ),
    ]
