# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170610_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
