# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20170706_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='в активные'),
        ),
    ]
